# Generated by Django 6.0.5 on 2026-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_devicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_digests',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_cancellation',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_delivery',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_order_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='enable_browser_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='enable_sound',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='general_notifications',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='order_confirmation',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='order_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='quiet_hours_start',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='rider_assignments',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable all notifications'),
        ),
    ]
